---
title: "Referenzen"
format: html
editor: visual
---

## Unterricht

"Eine *Definition von Unterricht* kann deskriptiv oder präskriptiv erfolgen. Deskriptive Vorgehensweisen orientieren sich an den realen Gegebenheiten vorfindlichen Unterrichts, präskriptive Vorgehensweisen an "normativen Vorstellungen, an theoretisch entwickelten Zielen oder an bestimmten, empirisch ermittelten Forschungsbefunden" (Bohl / Kucharz, 2010, 19)

Unterricht = komplexes Geschehen (vgl. Bohl et al., 2015, S.46 f.) \* Multidimensionalität \* Simulatanität \* Unmittelbarkeit \* Unvorhersehbarkeit \* Öffentlichkeit \* Historizität \* Intransparenz \* Informalität

Allgemeine Didaktik = Analyse und Gestaltung von Unterricht

aptitude-treatment-interaction (ATI) = Wechselwirkung zwischen Lehrmethode und Schülermerkmalen

TIMSS-Videostudie: MAtheunterricht in Vereinigten Staaten, Japan und DE

"Zukünftige Forschung wird vermutlich noch deutlicher als bisher erkennbar machen müssen, dass Merkmale der UQ, die derzeit als überfachlich bezeichnet werden, sich in differenten Fächern unterschiedlich darstellen (z.B. Kognitive Aktivierung), während andere Merkmale in der Tat für alle Fächer in ähnlicher Weise gelten dürften (z.B. Klassenführung; vgl, Praetorius, 2014)" (Bohl et al., 2015, S.55)

"But suppose the teacher beats the children into
attention, or drugs them so they are docile, or tempts them by dispensing illicit favors
for top performers? Again we see that teaching may be successful, in the sense that
all the students learn well what is being taught, but we withhold a judgment of quality
because we are sure the methods used are improper, even immoral" (Fenstermacher & Richardson, 2005, p.6)

"Quality teaching, it seems, pertains to what is taught
and how it is taught" (Fenstermacher & Richardson, 2005, p.6)

"To sharpen the contrast with successful
teaching, we will call teaching that accords with high standards for subject matter content and methods of practice good teaching. Successful teaching is teaching that yields the intended learning." (Fenstermacher & Richardson, 2005, p.6)

"Good teaching is grounded in the task sense of teaching, while successful teaching is grounded in the achievement sense of the term" (Fenstermacher & Richardson, 2005, p.6)

"successful teaching (evidence of student learning)" (Fenstermacher & Richardson, 2005, p.6)

